sonar.projectKey=fourreal-sysout_fourreal-web-client-mvp
sonar.organization=fourreal-sysout

sonar.sources=src
sonar.tests=src
sonar.exclusions=node_modules/**,dist/**,build/**
sonar.sourceEncoding=UTF-8
