sonar.projectKey=fourreal-sysout_fourreal-web-client-mvp
sonar.organization=fourreal-sysout

sonar.sources=src
sonar.tests=src/**/*.test.ts,src/**/*.spec.ts
sonar.exclusions=node_modules/**,dist/**,build/**
sonar.sourceEncoding=UTF-8
